import { User } from "./user";

export const USERS: User[] = [
    {
        id: 1,
        pseudo: "Wolfi",
        firstName: 'Wolfgang Amadeus',
        lastName: 'Mozart',
        email: 'wa-mozart@gmail.com',
        phone: '0658789874',
        job: 'musician',
        biography: `Après deux ans passés à Vienne je suis à la recherche d'un poste de compositeur à temps plein sur le secteur de Salzbourg. J'aime la musique et suis passioné d'ornithologie`,
        password: 'aA1@yuiyiyuyuyi',
        role: 'ADMIN',
        subscriptionDate: new Date(),
        teamInCommon: true,
        avatar: '../assets/mock/mozart.jpeg',
        picture:''
    },
    {
        id: 2,
        pseudo: "LudwiGdarK",
        firstName: 'Ludwig',
        lastName: 'von Beethoven',
        email: 'beethov@gmail.com',
        phone: '0685467890',
        job: 'musician',
        biography: `Après avoir fondé l'association des sourds de Franckfort, je compose aujourd'hui des opéras pour chanteurs muets`,
        password: 'aA1@yuiyiyuyuyi',
        role: 'USER',
        subscriptionDate: new Date(),
        teamInCommon: false,
        avatar: '../assets/mock/Beethoven.jpeg',
        picture:''
    },
    {
        id: 3,
        pseudo: "ChopinouDu63",
        firstName: 'Frédéric',
        lastName: 'Chopin',
        email: 'frederic-chopin@free.fr',
        phone: '0178497856',
        job: 'compositeur',
        biography: `Après 6 ans de dépression et une cure de désintoxiaction à l'absinthe je reviens à Paris pour reconquérir mon public`,
        password: 'aA1@yuiyiyuyuyi',
        role: 'USER',
        subscriptionDate: new Date(),
        teamInCommon: false,
        avatar: '../assets/mock/Chopin.jpeg',
        picture:''
    },
    {
        id: 4,
        pseudo: "NapoPo_corsica5",
        firstName: 'Napoléon',
        lastName: 'Bonaparte',
        email: 'bonaparte@yahoo.com',
        phone: '0188492156',
        job: 'artilleur, général, empereur',
        biography: `Actuellement en congé sabbatique à Saint-Hélène, je profite de mon temps libre pour faire une collection de timbres`,
        password: 'aA1@yuiyiyuyuyi',
        role: 'USER',
        subscriptionDate: new Date(),
        teamInCommon: true,
        avatar: '../assets/mock/bonaparte.jpg',
        picture:''
    },
    {
        id: 5,
        pseudo: "Pucelle8_Orleans",
        firstName: 'Jeanne',
        lastName: "D'arc",
        email: 'jeanneA@free.fr',
        phone: '0657397878',
        job: 'Bergère',
        biography: `Je suis actuellement en recherche spirituelle`,
        password: 'aA1@yuiyiyuyuyi',
        role: 'USER',
        subscriptionDate: new Date(),
        teamInCommon: false,
        avatar: '../assets/mock/Jeanne_arc.jpg',
        picture:''
    },
    {
        id: 6,
        pseudo: "YvesMonMon",
        firstName: 'Yves',
        lastName: "Montant",
        email: 'montant-yves2@orange.fr',
        phone: '0634978458',
        job: 'Chanteur interprête, acteurr',
        biography: "J'aime la chanson et les films de Audiard",
        password: 'aA1@yuiyiyuyuyi',
        role: 'USER',
        subscriptionDate: new Date(),
        teamInCommon: false,
        avatar: '../assets/mock/Montand.jpeg',
        picture:''
    },
    {
        id: 7,
        pseudo: "Foot_King",
        firstName: 'Kyllian',
        lastName: "Mbappé",
        email: 'mbpKi2@gmail.com',
        phone: '0785698745',
        job: 'Footballeur',
        biography: "je suis passioné de football et collectionne les huiles essentielles",
        password: 'aA1@yuiyiyuyuyi',
        role: 'USER',
        subscriptionDate: new Date(),
        teamInCommon: false,
        avatar: '../assets/mock/Mbappe.webp',
        picture:''
    },
    {
        id: 8,
        pseudo: "NadetteDePanam",
        firstName: 'Bernadette',
        lastName: "Chirac",
        email: 'chirac-bernadette@mairie-de-neuilly.fr',
        phone: '0185467842',
        job: 'Retraité',
        biography: "Je collectionne les pièces jaunes. Vous pouvez m'en envoyer via le portail piecesjaunes.fr",
        password: 'aA1@yuiyiyuyuyi',
        role: 'USER',
        subscriptionDate: new Date(),
        teamInCommon: false,
        avatar: '../assets/mock/Bernadette_chirac.jpg',
        picture:''
    },
    {
        id: 9,
        pseudo: "CueilleurChasseur",
        firstName: 'Homme',
        lastName: "De Néandertal",
        email: 'groumpf@orange.fr',
        phone: '072456845',
        job: 'Chasseur-cueilleur',
        biography: "grompf groumpf roumf roufm",
        password: 'aA1@yuiyiyuyuyi',
        role: 'USER',
        subscriptionDate: new Date(),
        teamInCommon: false,
        avatar: '../assets/mock/Neandertal.jpg',
        picture:''
    },{
        id: 10,
        pseudo: "Incognito",
        firstName: 'monsieur',
        lastName: "X",
        email: 'incognito@inote.fr',
        phone: 'xxxxxxxxx',
        job: 'inconnu',
        biography: "je suis un inconnu",
        password: 'aA1@yuiyiyuyuyi',
        role: 'USER',
        subscriptionDate: new Date(),
        teamInCommon: false,
        avatar: '',
        picture:''
    },

    
    


    
    
    
]